marks=(85, 90, 78, 92, 88)
max_marks=max(marks)
min_marks=min(marks)    
sum_marks=sum(marks)
length=len(marks)
print("Maximum marks:", max_marks)
print("Minimum marks:", min_marks)
print("Sum of marks:", sum_marks)
print("Number of students:", length)