name=("Alice", "Bob", "Charlie")
age=(20, 25, 30)
branch=("Computer Science", "Mathematics", "Physics")
print("Name:", name[0])
print("Age:", age[0])
print("Branch:", branch[0])
print("Name:", name[1])
print("Age:", age[1])
print("Branch:", branch[1])
print("Name:", name[2])
print("Age:", age[2])
print("Branch:", branch[2])